# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/paar',
                'doc_host': 'https://vedicreader.github.io',
                'git_url': 'https://github.com/vedicreader/paar',
                'lib_path': 'paar'},
  'syms': {'paar.core': {'paar.core.foo': ('core.html#foo', 'paar/core.py')}}}
