"""Restricted execution for AI agents over the owner's live namespace: an overlay layer
(agents read everything, create their own names, and can never rebind or delete the
owner's) plus a clikernel-compatible inspector hook — an AST restriction list checked
before every cell runs.

Docs: https://vedicreader.github.io/paar/agent.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/10_agent.ipynb.

# %% auto #0
__all__ = ['RuleBlock', 'load_inspectors', 'run_inspectors', 'policy_inspectors', 'AgentSession']

# %% ../nbs/10_agent.ipynb #10-c4
import ast, os, runpy, inspect
from pathlib import Path
from IPython.utils.capture import capture_output
from .runtime import ExecResult, _exec_capture, _flat_result
from .snapshot import snapshot, expand, grid_page, profile_view
from .bridge import _ns

try: from clikernel.base import RuleBlock as _RuleBlockBase   # subclass it so clikernel's own `except RuleBlock` catches a paar inspector's block
except ImportError: _RuleBlockBase = Exception

class RuleBlock(_RuleBlockBase):
    "Raised by an inspector to deliberately block a cell; any other inspector exception is a bug and fails open (clikernel-compatible)."

# %% ../nbs/10_agent.ipynb #10-c5
def load_inspectors(path=None):
    "Inspector functions from `path`, $PAAR_INSPECTORS, or ~/.config/paar/inspectors.py; the file may define `inspect(tree[, code])` and/or a list `inspectors` (clikernel's file contract)."
    p = path or os.environ.get('PAAR_INSPECTORS') or Path(os.environ.get('XDG_CONFIG_HOME', str(Path.home()/'.config')))/'paar'/'inspectors.py'
    p = Path(p).expanduser()
    if not p.exists(): return []
    ns = runpy.run_path(str(p))
    ins = list(ns.get('inspectors', []))
    if callable(ns.get('inspect')): ins.append(ns['inspect'])
    return ins

def _call_inspector(f, tree, code):
    "1-arg inspectors get the transformed AST; 2-arg ones also get the raw cell source."
    return f(tree, code) if len(inspect.signature(f).parameters) > 1 else f(tree)

def run_inspectors(inspectors, code):
    "Concatenated notes from every inspector for `code` ('' for unparseable code — execution reports the syntax error); RuleBlock propagates, any other inspector exception fails open with a warning note."
    try: tree = ast.parse(code)
    except SyntaxError: return ''
    notes = []
    for f in inspectors:
        try: n = _call_inspector(f, tree, code)
        except RuleBlock: raise
        except Exception as e: n = f'[inspector {getattr(f, "__name__", "?")} crashed, check skipped: {type(e).__name__}: {e}]\n'
        if n: notes.append(n)
    return ''.join(notes)

# %% ../nbs/10_agent.ipynb #10-c7
_MUTATORS = frozenset('append extend insert remove pop clear update add discard popitem setdefault sort reverse'.split())
_BLOCKED_CALLS = frozenset('exec eval setattr delattr globals vars breakpoint'.split())
_DESTRUCTIVE = {('os','remove'),('os','unlink'),('os','rmdir'),('os','removedirs'),('os','rename'),
                ('os','replace'),('os','system'),('os','popen'),('shutil','rmtree'),('shutil','move')}
_DESTRUCTIVE_ATTRS = frozenset(('rmtree','unlink','rmdir'))

def _root(node):
    "Base Name id of a dotted/indexed/called chain (x.a[0].b() -> 'x'), or None."
    while isinstance(node, (ast.Attribute, ast.Subscript, ast.Call)):
        node = node.func if isinstance(node, ast.Call) else node.value
    return node.id if isinstance(node, ast.Name) else None

def _block(msg): raise RuleBlock(msg)

def _check_del(node, owner):
    for t in node.targets:
        r = t.id if isinstance(t, ast.Name) else _root(t)
        if r in owner: _block(f"cannot delete owner variable '{r}'; you may only delete names you created")

def _check_assign(node, owner):
    tgts = node.targets if isinstance(node, ast.Assign) else [node.target]
    for t in tgts:
        for u in ast.walk(t):   # covers tuple/list unpacking targets
            if isinstance(u, (ast.Attribute, ast.Subscript)):
                r = _root(u)
                if r in owner: _block(f"cannot modify owner variable '{r}' in place; bind your result to a new name instead")
    if isinstance(node, ast.AugAssign) and isinstance(node.target, ast.Name) and node.target.id in owner:
        _block(f"'{node.target.id} += ...' may mutate the owner's object in place; use a new name, e.g. {node.target.id}2 = {node.target.id} + ...")

def _check_call(node, owner):
    f = node.func
    if isinstance(f, ast.Name) and f.id in _BLOCKED_CALLS:
        _block(f"call to '{f.id}' is not allowed in the agent session")
    if isinstance(f, ast.Attribute):
        r = _root(f.value)
        if r == 'subprocess' or (isinstance(f.value, ast.Name) and (f.value.id, f.attr) in _DESTRUCTIVE):
            _block(f"'{r}.{f.attr}' is a shell/filesystem escape and is not allowed in the agent session; use your own shell tool")
        if f.attr in _DESTRUCTIVE_ATTRS:
            _block(f"'.{f.attr}()' deletes resources and is not allowed in the agent session")
        if f.attr in _MUTATORS and r in owner:
            _block(f"'.{f.attr}()' would mutate owner variable '{r}'; copy it to a new name first")
        if r in owner and any(k.arg == 'inplace' and getattr(k.value, 'value', None) is True for k in node.keywords):
            _block(f"inplace=True would mutate owner variable '{r}'; drop inplace and bind the result to a new name")

def policy_inspectors(owner_names):
    "The default restriction list, closed over `owner_names` (a callable giving the currently protected names): agents may read owner variables and create their own; deleting, rebinding in place, or mutating owner state — and destructive file/shell escapes — are blocked."
    def guard(tree, code):
        owner = owner_names()
        for node in ast.walk(tree):
            if isinstance(node, ast.Delete): _check_del(node, owner)
            elif isinstance(node, (ast.Assign, ast.AugAssign, ast.AnnAssign)): _check_assign(node, owner)
            elif isinstance(node, ast.Call): _check_call(node, owner)
            elif isinstance(node, ast.Attribute) and node.attr in ('__dict__', '__globals__') and _root(node) in owner:
                _block(f"direct '{node.attr}' access on owner objects is not allowed")
        return None
    return [guard]

# %% ../nbs/10_agent.ipynb #10-c9
class AgentSession:
    "A persistent agent overlay on the owner namespace: reads fall through, writes land in the agent's own layer, and every cell passes the restriction list first."
    def __init__(self,
                 owner=None,   # callable -> namespace dict to protect (default: paar's inspected namespace)
                 rules=None):  # extra inspectors appended to the default policy (default: load_inspectors())
        self.owner = owner if owner is not None else _ns
        self.layer = {}   # names the agent created (or shadowed)
        self.ns = {}      # persistent exec globals: owner view + layer
        self.inspectors = policy_inspectors(self.owner_names) + (load_inspectors() if rules is None else list(rules))

    def owner_names(self):
        "Currently protected names: everything in the owner namespace the agent hasn't shadowed."
        return {k for k in self.owner() if k not in self.layer}

    def _sync_in(self):
        owner = self.owner()
        for k, v in owner.items():
            if k not in self.layer: self.ns[k] = v
        for k in [k for k in self.ns if k not in owner and k not in self.layer and k != '__builtins__']:
            del self.ns[k]   # owner deleted it; the agent's view follows
        return self.ns

    def _sync_out(self):
        owner = self.owner()
        for k, v in self.ns.items():
            if k != '__builtins__' and owner.get(k) is not v: self.layer[k] = v
        for k in [k for k in self.layer if k not in self.ns]: del self.layer[k]

    def view_ns(self):
        "Merged read view (owner + agent layer) for snapshots/expands/grids."
        return {k: v for k, v in self._sync_in().items() if k != '__builtins__'}

    def run(self, code, scope='overlay'):
        "Run agent code under the restriction list. scope='overlay' persists new names in the agent layer; 'isolated' discards all writes. The owner namespace is never written either way."
        try: note = run_inspectors(self.inspectors, code)
        except RuleBlock as e: return ExecResult(ok=False, error=f'blocked: {e}')
        run_ns = self._sync_in() if scope == 'overlay' else dict(self._sync_in())
        cap = err = val = None
        try:
            with capture_output() as cap: val = _exec_capture(code, run_ns)
        except Exception as e:
            err = f'{type(e).__name__}: {e}'
        if scope == 'overlay': self._sync_out()
        out = note + (cap.stdout if cap is not None else '')
        if err: return ExecResult(ok=False, stdout=out, error=err)
        return ExecResult(ok=True, result=None if val is None else _flat_result(val), stdout=out)

    def snapshot(self, name=None, typ=None): return snapshot(self.view_ns(), frozenset(), name, typ)
    def view(self, profile='standard'): return profile_view(self.view_ns(), frozenset(), profile)
    def expand(self, accessor, offset=0): return expand(self.view_ns(), accessor, offset)
    def grid(self, accessor, roff=0, coff=0, rows=50, cols=50): return grid_page(self.view_ns(), accessor, roff, coff, rows, cols)
