"""IPython namespace bridge

Docs: https://vedicreader.github.io/paar/bridge.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/04_bridge.ipynb.

# %% auto #0
__all__ = ['set_namespace', 'Bridge', 'on_change']

# %% ../nbs/04_bridge.ipynb #a0000020
from .snapshot import snapshot, expand, grid_page, profile_view
try: from IPython import get_ipython
except Exception:
    def get_ipython(): return None

_ns_override = None   # set by paar.fasthtml.serve() to inspect a plain process's namespace

def set_namespace(ns):
    "Point the bridge at an explicit namespace dict (headless/non-IPython use); None restores the IPython path."
    global _ns_override; _ns_override = ns

def _ns():
    if _ns_override is not None: return _ns_override
    ip = get_ipython(); return ip.user_ns if ip else {}

def _hidden():
    if _ns_override is not None: return frozenset()
    ip = get_ipython()
    return frozenset(getattr(ip, 'user_ns_hidden', ())) if ip else frozenset()

class Bridge:
    "Frontend-agnostic access to the live kernel namespace."
    def snapshot(self): return snapshot(_ns(), _hidden())
    def view(self, profile='standard'): return profile_view(_ns(), _hidden(), profile)
    def expand(self, accessor, offset=0): return expand(_ns(), accessor, offset)
    def grid(self, accessor, roff=0, coff=0, rows=50, cols=50): return grid_page(_ns(), accessor, roff, coff, rows, cols)

def on_change(cb):
    "Register cb() to fire after each cell execution; returns False outside IPython."
    ip = get_ipython()
    if not ip: return False
    ip.events.register('post_run_cell', lambda res: cb())
    return True
