"""IPython namespace bridge

Docs: https://vedicreader.github.io/paar/bridge.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/04_bridge.ipynb.

# %% auto #0
__all__ = ['Bridge', 'on_change']

# %% ../nbs/04_bridge.ipynb #a0000020
from .snapshot import snapshot, expand
try: from IPython import get_ipython
except Exception:
    def get_ipython(): return None

def _ns():
    ip = get_ipython(); return ip.user_ns if ip else {}

def _hidden():
    ip = get_ipython()
    return frozenset(getattr(ip, 'user_ns_hidden', ())) if ip else frozenset()

class Bridge:
    "Frontend-agnostic access to the live kernel namespace."
    def snapshot(self): return snapshot(_ns(), _hidden())
    def expand(self, accessor): return expand(_ns(), accessor)

def on_change(cb):
    "Register cb() to fire after each cell execution; returns False outside IPython."
    ip = get_ipython()
    if not ip: return False
    ip.events.register('post_run_cell', lambda res: cb())
    return True
