"""IPython namespace bridge

Docs: https://vedicreader.github.io/paar/bridge.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/04_bridge.ipynb.

# %% auto #0
__all__ = ['Bridge', 'on_change']

# %% ../nbs/04_bridge.ipynb #a0000020
from .snapshot import snapshot, expand, grid_page, profile_view
from .runtime import set_value
try: from IPython import get_ipython
except Exception:
    def get_ipython(): return None

def _ns():
    ip = get_ipython(); return ip.user_ns if ip else {}

def _hidden():
    ip = get_ipython()
    return frozenset(getattr(ip, 'user_ns_hidden', ())) if ip else frozenset()

class Bridge:
    "Frontend-agnostic access to the live kernel namespace."
    def snapshot(self, name=None, typ=None): return snapshot(_ns(), _hidden(), name, typ)
    def view(self, profile='standard'): return profile_view(_ns(), _hidden(), profile)
    def expand(self, accessor, offset=0): return expand(_ns(), accessor, offset)
    def grid(self, accessor, roff=0, coff=0, rows=50, cols=50): return grid_page(_ns(), accessor, roff, coff, rows, cols)
    def set_value(self, accessor, expr): return set_value(accessor, expr)

def on_change(cb):
    "Register cb() to fire after each cell execution; returns False outside IPython."
    ip = get_ipython()
    if not ip: return False
    ip.events.register('post_run_cell', lambda res: cb())
    return True
