"""`VarInfo` — the one row shape every paar frontend consumes

Docs: https://vedicreader.github.io/paar/core.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% ../nbs/00_core.ipynb #da4d26dd
from __future__ import annotations
from dataclasses import dataclass

LAZY = '…'  # placeholder repr for values not yet evaluated (used from P1 onward)

@dataclass
class VarInfo:
    "One inspector row: a namespace binding or a container child."
    name:str
    type:str
    qualifier:str=''
    value:str=''
    shape:str|None=None
    dtype:str|None=None
    is_container:bool=False
    is_grid:bool=False
    is_error:bool=False
    path:str=''
    accessor:tuple=()
    more_offset:int|None=None   # set on the load-more sentinel: next offset to expand from

# %% auto #0
__all__ = ['LAZY', 'VarInfo']
