"""In-kernel live inspector panel served via FastHTML

Docs: https://vedicreader.github.io/paar/fasthtml.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/05_fasthtml.ipynb.

# %% auto #0
__all__ = ['bridge', 'app', 'home', 'rows', 'expand_route', 'live', 'inspector']

# %% ../nbs/05_fasthtml.ipynb #cell-export-imports
import asyncio, threading, json
from urllib.parse import quote
from fasthtml.common import *
from fasthtml.jupyter import JupyUvi, HTMX
from .bridge import Bridge, on_change
from .core import VarInfo

_css = Style('.paar-children{margin-left:1rem} .paar-toggle{cursor:pointer;user-select:none}')
bridge = Bridge()
app = FastHTML(exts='ws', hdrs=(_css,))   # ws ext + pico (default) + indentation css
_clients = []   # list[(loop, send)]
_clients_lock = threading.Lock()
_server = None

# %% ../nbs/05_fasthtml.ipynb #cell-export-rows
def _badges(v:VarInfo):
    "shape/dtype summary string for a row."
    return ' '.join(x for x in [v.shape and f'shape={v.shape}',
                                v.dtype and f'dtype={v.dtype}'] if x)

def _acc(accessor):
    "URL-safe encoding of a positional accessor."
    return quote(json.dumps(list(accessor)), safe='')

def _node(v:VarInfo):
    "Render one VarInfo as a tree node; containers get a ▸ toggle that lazily loads children."
    b = _badges(v)
    head = Span(Strong(v.name), ' ', Small(v.type, title=v.qualifier), ' ',
                Code(v.value), (' ' + b) if b else '',
                cls=('error' if v.is_error else None))
    if v.is_container:
        toggle = Span('▸', cls='paar-toggle', hx_get=f'/expand?accessor={_acc(v.accessor)}',
                      hx_target='next .paar-children', hx_swap='innerHTML')
        return Div(Div(toggle, ' ', head), Div(cls='paar-children'), cls='paar-node')
    return Div(head, cls='paar-node')

def _rows_div():
    "The rendered snapshot as a node tree, wrapped in the #rows target."
    return Div(*[_node(v) for v in bridge.snapshot()], id='rows')

def _loader(oob=False):
    "A #rows div that immediately GETs /rows (used initially and as the WS nudge)."
    kw = dict(hx_get='/rows', hx_trigger='load', hx_swap='outerHTML')
    if oob: kw['hx_swap_oob']='true'
    return Div(id='rows', **kw)

# %% ../nbs/05_fasthtml.ipynb #cell-export-routes
@app.get('/')
def home():
    return Titled('paar', Div(_loader(), hx_ext='ws', ws_connect='/live', id='paar'))

@app.get('/rows')
def rows(): return _rows_div()

@app.get('/expand')
def expand_route(accessor:str):
    return Div(*[_node(v) for v in bridge.expand(tuple(json.loads(accessor)))])

def _drop(send):
    "Remove a client by its send identity (thread-safe)."
    with _clients_lock:
        _clients[:] = [(l,s) for (l,s) in _clients if s is not send]

async def _conn(send):
    with _clients_lock: _clients.append((asyncio.get_running_loop(), send))
async def _disconn(send): _drop(send)

@app.ws('/live', conn=_conn, disconn=_disconn)
async def live(send): pass

# %% ../nbs/05_fasthtml.ipynb #cell-export-broadcast
def _broadcast(fragment):
    "Push fragment to every WS client from any thread; drop clients that fail."
    with _clients_lock: targets = list(_clients)
    for loop, send in targets:
        try: fut = asyncio.run_coroutine_threadsafe(send(fragment), loop)
        except Exception: _drop(send); continue
        fut.add_done_callback(lambda f, s=send: (not f.cancelled()) and f.exception() is not None and _drop(s))

def inspector(port=8000, height=520):
    "Start the in-kernel live inspector panel and return the inline iframe."
    global _server
    if _server is None:
        _server = JupyUvi(app, port=port, daemon=True)
        on_change(lambda: _broadcast(to_xml(_loader(oob=True))))
    return HTMX(port=port, height=height, link=True)
