"""Gridable detection and paged array slicing

Docs: https://vedicreader.github.io/paar/grid.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/06_grid.ipynb.

# %% auto #0
__all__ = ['is_gridable', 'array_page', 'array_detail', 'frame_detail', 'series_detail', 'ArrayResolver', 'FrameResolver',
           'SeriesResolver']

# %% ../nbs/06_grid.ipynb #a0000020
import itertools
from .reprs import safe_repr
from .resolvers import Resolver, register_resolver
try: import numpy as np
except Exception: np = None
try: import pandas as pd
except Exception: pd = None

def is_gridable(v):
    "True for a numpy ndarray (1-2D) or a pandas DataFrame/Series."
    if np is not None and isinstance(v, np.ndarray): return v.ndim in (1, 2)
    if pd is not None and isinstance(v, (pd.DataFrame, pd.Series)): return True
    return False

def _cell(x): return safe_repr(x, 40)

def array_page(v, roff=0, coff=0, rows=50, cols=50):
    "Page a gridable value -> dict(headers,index,cells,nrows,ncols,roff,coff,rows,cols), or None."
    if pd is not None and isinstance(v, pd.DataFrame):
        nrows, ncols = v.shape
        sub = v.iloc[roff:roff+rows, coff:coff+cols]
        headers = [str(c) for c in sub.columns]
        index = [str(i) for i in sub.index]
        cells = [[_cell(x) for x in row] for row in sub.values.tolist()]
    elif pd is not None and isinstance(v, pd.Series):
        nrows, ncols = v.shape[0], 1
        sub = v.iloc[roff:roff+rows]
        headers = [str(v.name) if v.name is not None else 'value']
        index = [str(i) for i in sub.index]
        cells = [[_cell(x)] for x in sub.tolist()]
    elif np is not None and isinstance(v, np.ndarray) and v.ndim == 2:
        nrows, ncols = v.shape
        sub = v[roff:roff+rows, coff:coff+cols]
        headers = [str(c) for c in range(coff, min(coff+cols, ncols))]
        index = [str(r) for r in range(roff, min(roff+rows, nrows))]
        cells = [[_cell(x) for x in row] for row in sub.tolist()]
    elif np is not None and isinstance(v, np.ndarray) and v.ndim == 1:
        nrows, ncols = v.shape[0], 1
        sub = v[roff:roff+rows]
        headers = ['0']
        index = [str(r) for r in range(roff, min(roff+rows, nrows))]
        cells = [[_cell(x)] for x in sub.tolist()]
    else:
        return None
    return {'headers': headers, 'index': index, 'cells': cells,
            'nrows': nrows, 'ncols': ncols, 'roff': roff, 'coff': coff,
            'rows': rows, 'cols': cols}

# %% ../nbs/06_grid.ipynb #810a5530
_MAX_ELEMS = 90   # element rows generated per expand (metadata rows add on top; keeps total under snapshot MAX_CHILDREN)

def _stat(fn):
    "Call a numpy/pandas reduction, returning None if it raises (e.g. non-numeric data)."
    try: return fn()
    except Exception: return None

def array_detail(v):
    "Curated child rows for an ndarray: metadata, numeric stats, then indexed elements (capped)."
    rows = [('shape', '.shape', v.shape), ('dtype', '.dtype', v.dtype), ('size', '.size', v.size)]
    rows += [(nm, f'.{nm}()', s) for nm,fn in [('min',v.min),('max',v.max),('mean',v.mean),
                                               ('std',v.std),('sum',v.sum)] if (s:=_stat(fn)) is not None]
    rows += [(str(i), f'[{i}]', x) for i,x in itertools.islice(enumerate(v), _MAX_ELEMS)]
    n = len(v)
    if n > _MAX_ELEMS: rows.append(('…', '', f'{n-_MAX_ELEMS} more'))
    return rows

def frame_detail(v):
    "Curated child rows for a DataFrame: metadata then each column as a Series."
    return [('shape', '.shape', v.shape), ('size', '.size', v.size), ('dtypes', '.dtypes', v.dtypes),
            *[(str(c), f'[{c!r}]', v[c]) for c in v.columns]]

def series_detail(v):
    "Curated child rows for a Series: metadata then indexed elements (capped)."
    rows = [('dtype', '.dtype', v.dtype), ('size', '.size', v.size), ('name', '.name', v.name)]
    rows += [(str(ix), f'.iloc[{i}]', x) for i,(ix,x) in itertools.islice(enumerate(v.items()), _MAX_ELEMS)]
    n = len(v)
    if n > _MAX_ELEMS: rows.append(('…', '', f'{n-_MAX_ELEMS} more'))
    return rows

class ArrayResolver(Resolver):
    "Expands an ndarray into stats + element rows (peers the grid table)."
    def can(self, v): return np is not None and isinstance(v, np.ndarray) and v.ndim >= 1
    def children(self, v): return array_detail(v)

class FrameResolver(Resolver):
    "Expands a DataFrame into metadata + column Series."
    def can(self, v): return pd is not None and isinstance(v, pd.DataFrame)
    def children(self, v): return frame_detail(v)

class SeriesResolver(Resolver):
    "Expands a Series into metadata + element rows."
    def can(self, v): return pd is not None and isinstance(v, pd.Series)
    def children(self, v): return series_detail(v)

for _r in (ArrayResolver(), FrameResolver(), SeriesResolver()): register_resolver(_r)
