"""Gridable detection and paged array slicing

Docs: https://vedicreader.github.io/paar/grid.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/06_grid.ipynb.

# %% auto #0
__all__ = ['is_gridable', 'array_page']

# %% ../nbs/06_grid.ipynb #a0000020
from .reprs import safe_repr
try: import numpy as np
except Exception: np = None
try: import pandas as pd
except Exception: pd = None

def is_gridable(v):
    "True for a numpy ndarray (1-2D) or a pandas DataFrame/Series."
    if np is not None and isinstance(v, np.ndarray): return v.ndim in (1, 2)
    if pd is not None and isinstance(v, (pd.DataFrame, pd.Series)): return True
    return False

def _cell(x): return safe_repr(x, 40)

def array_page(v, roff=0, coff=0, rows=50, cols=50):
    "Page a gridable value -> dict(headers,index,cells,nrows,ncols,roff,coff,rows,cols), or None."
    if pd is not None and isinstance(v, pd.DataFrame):
        nrows, ncols = v.shape
        sub = v.iloc[roff:roff+rows, coff:coff+cols]
        headers = [str(c) for c in sub.columns]
        index = [str(i) for i in sub.index]
        cells = [[_cell(x) for x in row] for row in sub.values.tolist()]
    elif pd is not None and isinstance(v, pd.Series):
        nrows, ncols = v.shape[0], 1
        sub = v.iloc[roff:roff+rows]
        headers = [str(v.name) if v.name is not None else 'value']
        index = [str(i) for i in sub.index]
        cells = [[_cell(x)] for x in sub.tolist()]
    elif np is not None and isinstance(v, np.ndarray) and v.ndim == 2:
        nrows, ncols = v.shape
        sub = v[roff:roff+rows, coff:coff+cols]
        headers = [str(c) for c in range(coff, min(coff+cols, ncols))]
        index = [str(r) for r in range(roff, min(roff+rows, nrows))]
        cells = [[_cell(x) for x in row] for row in sub.tolist()]
    elif np is not None and isinstance(v, np.ndarray) and v.ndim == 1:
        nrows, ncols = v.shape[0], 1
        sub = v[roff:roff+rows]
        headers = ['0']
        index = [str(r) for r in range(roff, min(roff+rows, nrows))]
        cells = [[_cell(x)] for x in sub.tolist()]
    else:
        return None
    return {'headers': headers, 'index': index, 'cells': cells,
            'nrows': nrows, 'ncols': ncols, 'roff': roff, 'coff': coff,
            'rows': rows, 'cols': cols}
