"""Value-string provider registry

Docs: https://vedicreader.github.io/paar/providers.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/07_providers.ipynb.

# %% auto #0
__all__ = ['register_str_provider', 'str_provider', 'provided_str', 'value_str']

# %% ../nbs/07_providers.ipynb #a0000020
import pathlib, datetime, enum, uuid
from .reprs import safe_repr
try: import numpy as np
except Exception: np = None
try: import pandas as pd
except Exception: pd = None

_PROVIDERS = []   # list[(type, fn)]

def register_str_provider(typ, fn):
    "Register fn(value)->str as the display string for instances of typ (and subclasses)."
    _PROVIDERS.append((typ, fn))

def str_provider(typ):
    "Decorator: @str_provider(T) registers the decorated fn as T's value-string provider."
    def deco(fn): register_str_provider(typ, fn); return fn
    return deco

def provided_str(v):
    "Custom display string for v (latest-registered isinstance match), or None."
    for typ, fn in reversed(_PROVIDERS):
        try:
            if isinstance(v, typ): return fn(v)
        except Exception:
            continue
    return None

def value_str(v):
    "Display string for v: a registered provider if any, else safe_repr(v)."
    s = provided_str(v)
    return s if s is not None else safe_repr(v)

def _bytes_str(b):
    h = bytes(b[:8]).hex()
    return f'{h}… ({len(b)} bytes)' if len(b) > 8 else f'{h} ({len(b)} bytes)'

register_str_provider(pathlib.Path, lambda p: str(p))
register_str_provider(datetime.date, lambda d: d.isoformat())
register_str_provider(datetime.time, lambda t: t.isoformat())
register_str_provider(datetime.datetime, lambda d: d.isoformat())
register_str_provider(enum.Enum, lambda e: f'{type(e).__name__}.{e.name}')
register_str_provider(uuid.UUID, lambda u: str(u))
register_str_provider(bytes, _bytes_str)
register_str_provider(bytearray, _bytes_str)
if np is not None:
    register_str_provider(np.ndarray, lambda a: f'ndarray shape={tuple(a.shape)} {a.dtype}')
if pd is not None:
    register_str_provider(pd.DataFrame, lambda d: f'DataFrame [{d.shape[0]}×{d.shape[1]}]')
    register_str_provider(pd.Series, lambda s: f'Series [{s.shape[0]}] {s.dtype}')
