"""Local discovery of running paar servers. Each `serve()` process writes a tiny
JSON entry here so any frontend (web or `paar-tui`) can list live environments
and switch between them — identified by repo/package name.

Docs: https://vedicreader.github.io/paar/registry.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/09_registry.ipynb.

# %% auto #0
__all__ = ['reg_dir', 'env_name', 'free_port', 'register', 'unregister', 'active']

# %% ../nbs/09_registry.ipynb #09-c3
import os, json, socket, subprocess, time
from pathlib import Path

def reg_dir():
    "Directory holding one JSON file per live paar server (override with $PAAR_REG_DIR)."
    d = Path(os.environ.get('PAAR_REG_DIR', Path.home()/'.paar'/'reg'))
    d.mkdir(parents=True, exist_ok=True); return d

def _git_name(cwd=None):
    "Basename of the enclosing git repo, or None."
    try:
        r = subprocess.run(['git','-C',str(cwd or Path.cwd()),'rev-parse','--show-toplevel'],
                           capture_output=True, text=True, timeout=2)
        if r.returncode==0 and r.stdout.strip(): return Path(r.stdout.strip()).name
    except Exception: pass
    return None

def _pkg_name(ns):
    "Top-level package name inferred from a namespace's __package__/__name__, or None."
    if not ns: return None
    for k in ('__package__','__name__'):
        v = ns.get(k)
        if v and v!='__main__': return str(v).split('.')[0]
    return None

def env_name(explicit=None, ns=None):
    "Env label: explicit > git repo name > package name > cwd basename."
    return explicit or _git_name() or _pkg_name(ns) or Path.cwd().name

def free_port(start=8000, tries=50):
    "First bindable TCP port at/after start."
    for p in range(start, start+tries):
        with socket.socket() as s:
            try: s.bind(('127.0.0.1', p)); return p
            except OSError: continue
    raise OSError(f'no free port in {start}..{start+tries}')

# %% ../nbs/09_registry.ipynb #09-c4
def _alive(pid):
    "Is a process with pid running?"
    try: os.kill(pid, 0)
    except ProcessLookupError: return False
    except PermissionError: return True
    except Exception: return False
    return True

def register(name, port, base=None):
    "Write this server's registry entry and return it."
    e = dict(name=name, port=port, pid=os.getpid(), cwd=str(Path.cwd()),
             base=base or f'http://127.0.0.1:{port}', started=time.time())
    (reg_dir()/f'{port}.json').write_text(json.dumps(e)); return e

def unregister(port):
    "Remove this server's registry entry."
    try: (reg_dir()/f'{port}.json').unlink()
    except FileNotFoundError: pass

def active():
    "Live registry entries, pruning any whose process has died."
    out = []
    for f in sorted(reg_dir().glob('*.json')):
        try: e = json.loads(f.read_text())
        except Exception: continue
        if _alive(e.get('pid', -1)): out.append(e)
        else:
            try: f.unlink()
            except Exception: pass
    return out
