"""Value rendering helpers

Docs: https://vedicreader.github.io/paar/reprs.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_reprs.ipynb.

# %% auto #0
__all__ = ['safe_repr', 'get_shape', 'get_dtype']

# %% ../nbs/01_reprs.ipynb #a0000020
def safe_repr(v, n=300):
    "repr(v) truncated to n chars, never raising."
    try: r = repr(v)
    except Exception as e: return f'<repr-error {type(e).__name__}: {e}>'
    return r if len(r)<=n else r[:n-1]+'…'

# %% ../nbs/01_reprs.ipynb #a0000021
def get_shape(v):
    "tuple(v.shape) as a string; else len(v) for sized non-strings; else None."
    try:
        s = getattr(v, 'shape', None)
        if s is not None and not callable(s): return str(tuple(s))
        if hasattr(v, '__len__') and not isinstance(v, (str, bytes, bytearray)):
            return str(len(v))
    except Exception:
        return None
    return None

# %% ../nbs/01_reprs.ipynb #a0000022
def get_dtype(v):
    "str(v.dtype) when present, else None."
    try:
        d = getattr(v, 'dtype', None)
        return str(d) if d is not None else None
    except Exception:
        return None
