"""Container resolver registry

Docs: https://vedicreader.github.io/paar/resolvers.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_resolvers.ipynb.

# %% auto #0
__all__ = ['Resolver', 'DictResolver', 'ListTupleResolver', 'SetResolver', 'ObjectResolver', 'resolve_for']

# %% ../nbs/02_resolvers.ipynb #a0000020
class Resolver:
    "Decides if a value is a container and yields its ordered children."
    def can(self, v): raise NotImplementedError
    def children(self, v): raise NotImplementedError   # -> list[(name, step, child)]

class DictResolver(Resolver):
    def can(self, v): return isinstance(v, dict)
    def children(self, v): return [(repr(k), f'[{k!r}]', val) for k,val in v.items()]

class ListTupleResolver(Resolver):
    def can(self, v): return isinstance(v, (list, tuple))
    def children(self, v): return [(str(i), f'[{i}]', x) for i,x in enumerate(v)]

class SetResolver(Resolver):
    def can(self, v): return isinstance(v, (set, frozenset))
    def children(self, v): return [(str(i), f'[{i}]', x) for i,x in enumerate(v)]

class ObjectResolver(Resolver):
    def can(self, v): return hasattr(v, '__dict__') and bool(vars(v))
    def children(self, v): return [(k, f'.{k}', val) for k,val in sorted(vars(v).items())]

_RESOLVERS = [DictResolver(), ListTupleResolver(), SetResolver(), ObjectResolver()]

def resolve_for(v):
    "First resolver that handles v, else None (None => not a container)."
    for r in _RESOLVERS:
        try:
            if r.can(v): return r
        except Exception: pass
    return None
