"""Container resolver registry

Docs: https://vedicreader.github.io/paar/resolvers.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_resolvers.ipynb.

# %% auto #0
__all__ = ['Resolver', 'DictResolver', 'ListTupleResolver', 'SetResolver', 'DequeResolver', 'ObjectResolver', 'register_resolver',
           'resolve_for']

# %% ../nbs/02_resolvers.ipynb #a0000020
import inspect
from collections import deque

class Resolver:
    "Decides if a value is a container and yields its ordered children."
    def can(self, v): raise NotImplementedError
    def children(self, v): raise NotImplementedError   # -> list[(name, step, child)]

class DictResolver(Resolver):
    def can(self, v): return isinstance(v, dict)
    def children(self, v): return [(repr(k), f'[{k!r}]', val) for k,val in v.items()]

class ListTupleResolver(Resolver):
    def can(self, v): return isinstance(v, (list, tuple))
    def children(self, v): return [(str(i), f'[{i}]', x) for i,x in enumerate(v)]

class SetResolver(Resolver):
    "Sets: positional children in a stable order (sorted by repr); path fragment is display-only, not index-addressable."
    def can(self, v): return isinstance(v, (set, frozenset))
    def children(self, v): return [(str(i), f'[{i}]', x) for i,x in enumerate(sorted(v, key=repr))]

class DequeResolver(Resolver):
    "Deques: positional, index-addressable children (deque supports d[i])."
    def can(self, v): return isinstance(v, deque)
    def children(self, v): return [(str(i), f'[{i}]', x) for i,x in enumerate(v)]

_LEAF = (bool, int, float, complex, str, bytes, bytearray, type(None))   # never expandable

def _slot_names(v):
    "Slot names declared across v's MRO (excluding __dict__/__weakref__)."
    out = []
    for c in type(v).__mro__:
        s = getattr(c, '__slots__', ())
        if isinstance(s, str): s = (s,)
        out += [n for n in s if n not in ('__dict__', '__weakref__')]
    return out

class ObjectResolver(Resolver):
    "Catch-all like pydev's DefaultResolver: dir()-based children so __slots__ objects, properties and class attrs all expand; dunders and callables are skipped."
    def can(self, v):
        if isinstance(v, _LEAF): return False
        return bool(getattr(v, '__dict__', None)) or bool(_slot_names(v)) or hasattr(v, '__members__')
    def _keep(self, v, k):
        if k.startswith('__') and k.endswith('__'): return False
        try: a = getattr(v, k)
        except Exception: return True   # surface attribute errors as a child rather than hide the name
        return not (inspect.isroutine(a) or inspect.isbuiltin(a) or inspect.ismodule(a))
    def children(self, v):
        names = dir(v) or list(getattr(v, '__members__', ()))
        out = []
        for k in sorted(n for n in names if self._keep(v, n)):
            try: out.append((k, f'.{k}', getattr(v, k)))
            except Exception as e: out.append((k, f'.{k}', f'<error {type(e).__name__}: {e}>'))
        return out

_RESOLVERS = [DictResolver(), ListTupleResolver(), SetResolver(), DequeResolver(), ObjectResolver()]

def register_resolver(r, last=False):
    "Register a resolver; inserted before the catch-all ObjectResolver unless last=True."
    _RESOLVERS.insert(len(_RESOLVERS) if last else len(_RESOLVERS)-1, r)

def resolve_for(v):
    "First resolver that handles v, else None (None => not a container)."
    for r in _RESOLVERS:
        try:
            if r.can(v): return r
        except Exception: pass
    return None
