"""Execute code and edit values in the live kernel namespace

Docs: https://vedicreader.github.io/paar/runtime.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/08_runtime.ipynb.

# %% ../nbs/08_runtime.ipynb #68946c6e
from __future__ import annotations
from dataclasses import dataclass
import ast, datetime, re
from pathlib import Path
from .core import VarInfo
from .snapshot import _var_info, _walk
from .providers import value_str
from IPython.utils.capture import capture_output
from fastcore.nbio import read_nb, write_nb, new_nb, mk_cell
try: from IPython import get_ipython
except Exception:
    def get_ipython(): return None

@dataclass
class ExecResult:
    "Outcome of running code: last value as an inspector row, captured stdout, and error text."
    ok: bool
    result: VarInfo|None = None
    stdout: str = ''
    error: str|None = None

def _fmt_err(res):
    "Formatted exception text from a run_cell result, or None."
    e = getattr(res, 'error_in_exec', None) or getattr(res, 'error_before_exec', None)
    return f'{type(e).__name__}: {e}' if e is not None else None

def _exec_capture(code, ns):
    "Exec statements in ns; return the value of a trailing expression, else None."
    block = ast.parse(code)
    value = None
    if block.body and isinstance(block.body[-1], ast.Expr):
        last = ast.Expression(block.body.pop().value)
        exec(compile(block, '<paar>', 'exec'), ns)
        value = eval(compile(last, '<paar>', 'eval'), ns)
    else:
        exec(compile(block, '<paar>', 'exec'), ns)
    return value

def _flat_result(val):
    "A non-expandable result row (isolated mode leaves nothing reachable in user_ns)."
    return VarInfo(name='result', type=type(val).__name__, value=value_str(val))

def _ns_complete(code, pos):
    "Namespace completion fallback when there is no IPython kernel (headless serve())."
    import builtins, keyword
    from paar.bridge import _ns
    ns = _ns()
    tok = re.search(r'[\w.]*$', code[:pos]).group(0)
    if not tok: return {'from': pos, 'matches': []}
    if '.' in tok:
        base, _, prefix = tok.rpartition('.')
        try: obj = eval(base, {'__builtins__': builtins}, ns)     # evaluated in the inspected namespace only
        except Exception: return {'from': pos, 'matches': []}
        cands = [a for a in dir(obj) if a.startswith(prefix) and (prefix or not a.startswith('_'))]
        return {'from': pos - len(prefix), 'matches': sorted(cands)[:50]}
    names = set(ns) | set(dir(builtins)) | set(keyword.kwlist)
    cands = [n for n in names if n.startswith(tok)]
    return {'from': pos - len(tok), 'matches': sorted(cands)[:50]}

def _ip_complete(ip, code, pos):
    "Real IPython InteractiveShell.complete(text, line, cursor) -> (pre, matches); None if that signature doesn't apply."
    bol = code.rfind('\n', 0, pos) + 1                     # current physical line + cursor within it:
    eol = code.find('\n', pos); eol = len(code) if eol < 0 else eol   # gives IPython the `import ...`
    line, cur = code[bol:eol], pos - bol                   # context so venv modules complete too
    token = re.search(r'[\w.]*$', code[:pos]).group(0)
    cmp = getattr(ip, 'Completer', None)   # real kernel: legacy ip.complete() returns nothing while Jedi is on
    old = getattr(cmp, 'use_jedi', None)
    if cmp is not None: cmp.use_jedi = False
    try: pre, matches = ip.complete(token, line, cur)
    except Exception: return None
    finally:
        if old is not None: cmp.use_jedi = old   # restore so the user's own tab-completion keeps Jedi
    return {'from': pos - len(pre), 'matches': list(matches)[:50]}

def complete(code, pos):
    "Completions for the token ending at offset `pos` -> {'from': int, 'matches': [str]}. Handles execnb's CaptureShell completer (single-arg, what `serve` runs on), a real IPython kernel, and a headless namespace fallback."
    ip = get_ipython()
    if ip is None: return _ns_complete(code, pos)
    prefix = code[:pos]
    try: matches = ip.complete(prefix)   # execnb CaptureShell.complete(c) -> [tail matches]
    except Exception: matches = None
    if isinstance(matches, list):        # tail after the last dot is what those matches replace
        tail = re.search(r'[\w.]*$', prefix).group(0).rpartition('.')[-1]
        return {'from': pos - len(tail), 'matches': matches[:50]}
    return _ip_complete(ip, code, pos) or {'from': pos, 'matches': []}

SESSION_DIR = Path('paar_sessions')
_SESSION = datetime.datetime.now().strftime('%Y%m%d-%H%M%S')

def _session_path():
    SESSION_DIR.mkdir(parents=True, exist_ok=True)
    return SESSION_DIR/f'session_{_SESSION}.ipynb'

def current_session(): return f'session_{_SESSION}'

def log_run(code):
    "Append `code` as a code cell to this session's notebook (best-effort; never raises)."
    try:
        p = _session_path()
        nb = read_nb(p) if p.exists() else new_nb([])
        nb['cells'].append(mk_cell(code))
        write_nb(nb, p)
    except Exception: pass

def list_sessions():
    "Saved session notebooks, newest first, as [(stem, n_code_cells)]."
    if not SESSION_DIR.exists(): return []
    out = []
    for p in sorted(SESSION_DIR.glob('session_*.ipynb'), reverse=True):
        try: n = sum(c.get('cell_type')=='code' for c in read_nb(p)['cells'])
        except Exception: n = 0
        out.append((p.stem, n))
    return out

def read_session(name):
    "Code-cell sources for session `name` (a session_* stem); [] if missing or name is unsafe."
    if '/' in name or chr(92) in name or not name.startswith('session_'): return []
    p = SESSION_DIR/f'{name}.ipynb'
    if not p.exists(): return []
    try: return [c['source'] for c in read_nb(p)['cells'] if c.get('cell_type')=='code']
    except Exception: return []

def run(code, scope='global'):
    "Run `code` in the kernel; scope='global' mutates user_ns, 'isolated' uses a scratch copy."
    ip = get_ipython()
    if ip is None: return ExecResult(ok=False, error='no IPython kernel')
    if scope == 'isolated':
        ns = dict(ip.user_ns)
        try:
            with capture_output() as cap:
                val = _exec_capture(code, ns)
            return ExecResult(ok=True, result=None if val is None else _flat_result(val), stdout=cap.stdout)
        except Exception as e:
            return ExecResult(ok=False, error=f'{type(e).__name__}: {e}')
    log_run(code)
    with capture_output() as cap:
        res = ip.run_cell(code, store_history=True)
    err = _fmt_err(res)
    result = _var_info('result', res.result, ('_',), '_') if res.result is not None else None
    return ExecResult(ok=bool(res.success) and err is None, result=result, stdout=cap.stdout, error=err)

def set_value(accessor, expr):
    "Assign `expr` (evaluated in user_ns) to the lvalue at `accessor`; return error text or None."
    ip = get_ipython()
    if ip is None: return 'no IPython kernel'
    try: _, path = _walk(ip.user_ns, tuple(accessor))
    except Exception as e: return f'bad accessor: {e}'
    try:
        exec(f'{path} = ({expr})', ip.user_ns)
        return None
    except Exception as e:
        return f'{type(e).__name__}: {e}'

# %% auto #0
__all__ = ['SESSION_DIR', 'ExecResult', 'complete', 'current_session', 'log_run', 'list_sessions', 'read_session', 'run',
           'set_value']
