"""Execute code and edit values in the live kernel namespace

Docs: https://vedicreader.github.io/paar/runtime.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/08_runtime.ipynb.

# %% ../nbs/08_runtime.ipynb #68946c6e
from __future__ import annotations
from dataclasses import dataclass
from .core import VarInfo
from .snapshot import _var_info
from .providers import value_str
from IPython.utils.capture import capture_output
try: from IPython import get_ipython
except Exception:
    def get_ipython(): return None

@dataclass
class ExecResult:
    "Outcome of running code: last value as an inspector row, captured stdout, and error text."
    ok: bool
    result: VarInfo|None = None
    stdout: str = ''
    error: str|None = None

def _fmt_err(res):
    "Formatted exception text from a run_cell result, or None."
    e = getattr(res, 'error_in_exec', None) or getattr(res, 'error_before_exec', None)
    return f'{type(e).__name__}: {e}' if e is not None else None

def run(code, scope='global'):
    "Run `code` in the kernel; scope='global' mutates user_ns, 'isolated' uses a scratch copy."
    ip = get_ipython()
    if ip is None: return ExecResult(ok=False, error='no IPython kernel')
    with capture_output() as cap:
        res = ip.run_cell(code, store_history=True)
    err = _fmt_err(res)
    result = _var_info('result', res.result, ('_',), '_') if res.result is not None else None
    return ExecResult(ok=bool(res.success) and err is None, result=result, stdout=cap.stdout, error=err)

# %% auto #0
__all__ = ['ExecResult', 'run']
