"""Flat namespace serializer

Docs: https://vedicreader.github.io/paar/snapshot.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_snapshot.ipynb.

# %% auto #0
__all__ = ['snapshot']

# %% ../nbs/03_snapshot.ipynb #a0000020
from .core import VarInfo
from .reprs import safe_repr, get_shape, get_dtype

def _var_info(name, v):
    "Build a flat VarInfo for one binding (P1: no container resolution)."
    try:
        return VarInfo(name=name, type=type(v).__name__,
                       qualifier=getattr(type(v), '__module__', '') or '',
                       value=safe_repr(v), shape=get_shape(v), dtype=get_dtype(v),
                       path=name)
    except Exception as e:
        return VarInfo(name=name, type='?', value=f'<error {e}>', is_error=True, path=name)

def snapshot(ns, hidden=frozenset()):
    "namespace dict -> sorted list[VarInfo], skipping hidden and dunder names."
    keys = sorted(k for k in ns if k not in hidden and not k.startswith('__'))
    return [_var_info(k, ns[k]) for k in keys]
