"""Flat namespace serializer

Docs: https://vedicreader.github.io/paar/snapshot.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_snapshot.ipynb.

# %% auto #0
__all__ = ['MAX_CHILDREN', 'snapshot', 'expand', 'grid_page']

# %% ../nbs/03_snapshot.ipynb #a0000020
from .core import VarInfo
from .reprs import safe_repr, get_shape, get_dtype
from .resolvers import resolve_for
from .grid import is_gridable, array_page

MAX_CHILDREN = 100

def _var_info(name, v, accessor, path):
    "Build a VarInfo for one value at the given accessor/path."
    try:
        gridable = is_gridable(v)
        return VarInfo(name=name, type=type(v).__name__,
                       qualifier=getattr(type(v), '__module__', '') or '',
                       value=safe_repr(v), shape=get_shape(v), dtype=get_dtype(v),
                       is_container=(not gridable) and resolve_for(v) is not None,
                       is_grid=gridable, path=path, accessor=accessor)
    except Exception as e:
        return VarInfo(name=name, type='?', value=f'<error {e}>', is_error=True,
                       path=path, accessor=accessor)

def snapshot(ns, hidden=frozenset()):
    "namespace dict -> sorted list[VarInfo], skipping hidden and dunder names."
    keys = sorted(k for k in ns if k not in hidden and not k.startswith('__'))
    return [_var_info(k, ns[k], (k,), k) for k in keys]

def _walk(ns, accessor):
    "Resolve a positional accessor (name, *idxs) to (object, readable_path). Raises KeyError/IndexError on bad path."
    name, *idxs = accessor
    obj, path = ns[name], name
    for i in idxs:
        r = resolve_for(obj)
        if r is None: raise KeyError(accessor)
        _, step, obj = r.children(obj)[i]
        path += step
    return obj, path

def expand(ns, accessor):
    "Return one level of children of the value at accessor, as VarInfo (capped at MAX_CHILDREN)."
    try:
        obj, path = _walk(ns, tuple(accessor))
    except Exception:
        return []
    r = resolve_for(obj)
    if r is None: return []
    kids = r.children(obj)
    out = [_var_info(nm, child, tuple(accessor)+(i,), path+step)
           for i,(nm, step, child) in enumerate(kids[:MAX_CHILDREN])]
    if len(kids) > MAX_CHILDREN:
        out.append(VarInfo(name='…', type='', value=f'{len(kids)-MAX_CHILDREN} more',
                           path=path, accessor=tuple(accessor)))
    return out

def grid_page(ns, accessor, roff=0, coff=0, rows=50, cols=50):
    "Walk accessor to a gridable object and return a page dict, or None."
    try:
        obj, _ = _walk(ns, tuple(accessor))
    except Exception:
        return None
    if not is_gridable(obj): return None
    return array_page(obj, roff, coff, rows, cols)
