"""Flat namespace serializer

Docs: https://vedicreader.github.io/paar/snapshot.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_snapshot.ipynb.

# %% auto #0
__all__ = ['MAX_CHILDREN', 'GROUPS', 'PROFILES', 'snapshot', 'expand', 'grid_page', 'category', 'profile_view']

# %% ../nbs/03_snapshot.ipynb #a0000020
from .core import VarInfo
from .reprs import get_shape, get_dtype
from .resolvers import resolve_for
from .grid import is_gridable, array_page
from .providers import value_str

MAX_CHILDREN = 100   # page size for one expand call

def _var_info(name, v, accessor, path):
    "Build a VarInfo for one value at the given accessor/path."
    try:
        return VarInfo(name=name, type=type(v).__name__,
                       qualifier=getattr(type(v), '__module__', '') or '',
                       value=value_str(v), shape=get_shape(v), dtype=get_dtype(v),
                       is_container=resolve_for(v) is not None,   # gridables are also expandable
                       is_grid=is_gridable(v), path=path, accessor=accessor)
    except Exception as e:
        return VarInfo(name=name, type='?', value=f'<error {e}>', is_error=True,
                       path=path, accessor=accessor)

def snapshot(ns, hidden=frozenset()):
    "namespace dict -> sorted list[VarInfo], skipping hidden and dunder names."
    keys = sorted(k for k in ns if k not in hidden and not k.startswith('__'))
    return [_var_info(k, ns[k], (k,), k) for k in keys]

def _walk(ns, accessor):
    "Resolve a positional accessor (name, *idxs) to (object, readable_path). Raises KeyError/IndexError on bad path."
    name, *idxs = accessor
    obj, path = ns[name], name
    for i in idxs:
        r = resolve_for(obj)
        if r is None: raise KeyError(accessor)
        _, step, obj = r.children(obj)[i]
        path += step
    return obj, path

def expand(ns, accessor, offset=0, limit=MAX_CHILDREN):
    "One level of children of the value at accessor as VarInfo, windowed to kids[offset:offset+limit]; a load-more sentinel (more_offset set) trails a partial window."
    try:
        obj, path = _walk(ns, tuple(accessor))
    except Exception:
        return []
    r = resolve_for(obj)
    if r is None: return []
    kids = r.children(obj)
    out = [_var_info(nm, child, tuple(accessor)+(offset+i,), path+step)
           for i,(nm, step, child) in enumerate(kids[offset:offset+limit])]
    if len(kids) > offset+limit:
        out.append(VarInfo(name='…', type='', value=f'{len(kids)-(offset+limit)} more',
                           path=path, accessor=tuple(accessor), more_offset=offset+limit))
    return out

def grid_page(ns, accessor, roff=0, coff=0, rows=50, cols=50):
    "Walk accessor to a gridable object and return a page dict, or None."
    try:
        obj, _ = _walk(ns, tuple(accessor))
        if not is_gridable(obj): return None
        return array_page(obj, roff, coff, rows, cols)
    except Exception:
        return None

# %% ../nbs/03_snapshot.ipynb #7d2fd848
import inspect

def category(name, v, hidden=frozenset()):
    "Classify a namespace entry: 'special' | 'module' | 'type' | 'function' | 'data'."
    if name in hidden or name.startswith('_') or name in ('In','Out','exit','quit','get_ipython'):
        return 'special'
    if inspect.ismodule(v): return 'module'
    if isinstance(v, type): return 'type'
    if callable(v): return 'function'
    return 'data'

GROUPS = {'special':'Special Variables', 'type':'Types', 'function':'Functions', 'module':'Modules'}

# profile -> per-category disposition: 'top' | 'group' | 'hidden' ('data' is always top-level)
PROFILES = {
    'minimal':  {'type':'hidden', 'function':'hidden', 'module':'hidden', 'special':'hidden'},
    'standard': {'type':'group',  'function':'group',  'module':'group',  'special':'group'},
    'full':     {'type':'top',    'function':'top',    'module':'top',    'special':'group'},
}

def profile_view(ns, hidden=frozenset(), profile='standard'):
    "Group a namespace per profile -> ordered list[(label|None, [VarInfo])] (label None renders flat)."
    disp = PROFILES.get(profile, PROFILES['standard'])
    cats = {}
    for k in sorted(ns):
        cats.setdefault(category(k, ns[k], hidden), []).append(_var_info(k, ns[k], (k,), k))
    out = [(None, cats.get('data', []))]
    for c in ('module', 'type', 'function', 'special'):
        vs = cats.get(c)
        if not vs: continue
        d = disp.get(c, 'group')
        if d == 'top':     out.append((None, vs))
        elif d == 'group': out.append((GROUPS[c], vs))
        # 'hidden' -> omit
    return [(lbl, vs) for lbl, vs in out if vs]
